version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  server:
    build: 
      context: ./server
    ports:
      - "3001:3001"
